### ISSUE TITLE
Typescript not support

### ISSUE THREAD

**Issue by Rstacx** [kuumoneko/edgegpt-js#4]

**Comment by kuumoneko** [comment]
hello, can you show your code? I'm still using it normally.

**Comment by Rstacx** [comment]
> hello, can you show your code? I'm still using it normally.

It says no types

**Comment by kuumoneko** [comment]
I will check it early. Thanks for your report

**Comment by Rstacx** [comment]
> I will check it early. Thanks for your report

Okay 👍

**Comment by kuumoneko** [comment]
> Okay 👍

uhm... I just tried the update; can you see if it works.

**Comment by Rstacx** [comment]
> > Okay 👍
> 
> uhm... I just tried the update; can you see if it works.

```
[nodemon] starting `ts-node src/app.ts`
/root/chat-api/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /root/chat-api/node_modules/bingai-js/index.js from /root/chat-api/src/routes/user/bing.ts not supported
.
Instead change the require of index.js in /root/chat-api/src/routes/user/bing.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/root/chat-api/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/root/chat-api/src/routes/user/bing.ts:17:21)
    at m._compile (/root/chat-api/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/root/chat-api/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/root/chat-api/src/routes/user.ts:20:32)
    at m._compile (/root/chat-api/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/root/chat-api/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/root/chat-api/src/app.ts:21:32)
    at m._compile (/root/chat-api/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/root/chat-api/node_modules/ts-node/dist/index.js:859:16)
    at phase4 (/root/chat-api/node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (/root/chat-api/node_modules/ts-node/dist/bin.js:54:12)
    at main (/root/chat-api/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/root/chat-api/node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by kuumoneko** [comment]
uhm... It's a error when you import `bingai-js` by using `const {} = require()` instead of `import {} from ""`
Let me see
if possible, try using ES6

**Comment by Rstacx** [comment]
> uhm... It's a error when you import `bingai-js` by using `const {} = require()` instead of `import {} from ""` Let me see if possible, try using ES6

`import { ChatBot, conversation_style } from "bingai-js";`

Same error

**Comment by kuumoneko** [comment]
Etou... did you change *type* in package.json to "module"

**Comment by Rstacx** [comment]
> Etou... did you change _type_ in package.json to "module"

Yes but no

**Comment by kuumoneko** [comment]
Ehh... if you build from typescript you should change target to es6 

At least it works for me

**Comment by Rstacx** [comment]
> Ehh... if you build from typescript you should change target to es6
> 
> At least it works for me

It is difficult for me to develop with nodemon.
Do you add bing image generation too?

**Comment by kuumoneko** [comment]
Oh no, I didn't add bing generation into this api

**Comment by kuumoneko** [comment]
To use `bingai-js` in Typescript, please install `bingai-js@1.7.1` or later 

This is my `tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "ES6",
    "lib": [
      "DOM",
      "ES6",
      "ES2015"
    ],
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "allowJs": true,
    "checkJs": true,
    "sourceMap": true,
    "removeComments": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

You should build by extension if you use vscode, then run .js file
